CREATE TABLE HRMS_EMPLOYEES (
    EMPLOYEE_ID          NUMBER,
    EMPLOYEE_CODE        VARCHAR2(30)  CONSTRAINT HRMSEMP_CODE_NN NOT NULL,
    FIRST_NAME           VARCHAR2(100) CONSTRAINT HRMSEMP_FIRST_NAME_NN NOT NULL,
    LAST_NAME            VARCHAR2(100) CONSTRAINT HRMSEMP_LAST_NAME_NN NOT NULL,
    CNIC                 VARCHAR2(20)  CONSTRAINT HRMSEMP_CNIC_NN NOT NULL,
    EMAIL                VARCHAR2(200) CONSTRAINT HRMSEMP_EMAIL_NN NOT NULL,
    MOBILE               VARCHAR2(50)  CONSTRAINT HRMSEMP_MOBILE_NN NOT NULL,
    DEPARTMENT_ID        NUMBER        CONSTRAINT HRMSEMP_DEPT_NN NOT NULL,
    DESIGNATION_ID       NUMBER        CONSTRAINT HRMSEMP_DSG_NN NOT NULL,
    GRADE_ID             NUMBER        CONSTRAINT HRMSEMP_GRADE_NN NOT NULL,
    EMPLOYMENT_TYPE_ID   NUMBER        CONSTRAINT HRMSEMP_EMPTYPE_NN NOT NULL,
    DATE_OF_JOINING      DATE DEFAULT TRUNC(SYSDATE) CONSTRAINT HRMSEMP_DOJ_NN NOT NULL,
    STATUS               VARCHAR2(30) DEFAULT 'ACTIVE' CONSTRAINT HRMSEMP_STATUS_NN NOT NULL,
    CREATED_BY           VARCHAR2(150),
    CREATED_ON           DATE DEFAULT SYSDATE,
    UPDATED_BY           VARCHAR2(150),
    UPDATED_ON           DATE DEFAULT SYSDATE,
    CONSTRAINT HRMSEMP_EMPID_PK PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT HRMSEMP_CODE_UK UNIQUE (EMPLOYEE_CODE),
    CONSTRAINT HRMSEMP_CNIC_UK UNIQUE (CNIC),
    CONSTRAINT HRMSEMP_EMAIL_UK UNIQUE (EMAIL),
    CONSTRAINT HRMSEMP_DEPT_FK FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES HRMS_DEPARTMENTS (DEPARTMENT_ID),
    CONSTRAINT HRMSEMP_DSG_FK FOREIGN KEY (DESIGNATION_ID)
        REFERENCES HRMS_DESIGNATIONS (DESIGNATION_ID),
    CONSTRAINT HRMSEMP_GRADE_FK FOREIGN KEY (GRADE_ID)
        REFERENCES HRMS_GRADES (GRADE_ID),
    CONSTRAINT HRMSEMP_EMPTYPE_FK FOREIGN KEY (EMPLOYMENT_TYPE_ID)
        REFERENCES HRMS_EMPLOYMENT_TYPES (EMPLOYMENT_TYPE_ID),
    CONSTRAINT HRMSEMP_STATUS_CK CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'TERMINATED', 'SUSPENDED')),
    CONSTRAINT HRMSEMP_CNIC_LEN_CK CHECK (LENGTH(TRIM(CNIC)) BETWEEN 13 AND 20)
);

CREATE SEQUENCE HRMS_EMPLOYEES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX HRMSEMP_NAME_IX ON HRMS_EMPLOYEES (LAST_NAME, FIRST_NAME);
CREATE INDEX HRMSEMP_DEPT_IX ON HRMS_EMPLOYEES (DEPARTMENT_ID);
CREATE INDEX HRMSEMP_DSG_IX ON HRMS_EMPLOYEES (DESIGNATION_ID);
CREATE INDEX HRMSEMP_GRADE_IX ON HRMS_EMPLOYEES (GRADE_ID);
CREATE INDEX HRMSEMP_EMPTYPE_IX ON HRMS_EMPLOYEES (EMPLOYMENT_TYPE_ID);
CREATE INDEX HRMSEMP_STATUS_IX ON HRMS_EMPLOYEES (STATUS);
CREATE INDEX HRMSEMP_DOJ_IX ON HRMS_EMPLOYEES (DATE_OF_JOINING);

CREATE OR REPLACE TRIGGER HRMSEMP_BIUR
    BEFORE INSERT OR UPDATE ON HRMS_EMPLOYEES
    FOR EACH ROW
DECLARE
    l_user VARCHAR2(150);
BEGIN
    l_user := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), USER);

    IF INSERTING THEN
        IF :NEW.EMPLOYEE_ID IS NULL THEN
            :NEW.EMPLOYEE_ID := HRMS_EMPLOYEES_SEQ.NEXTVAL;
        END IF;

        :NEW.CREATED_ON := COALESCE(:NEW.CREATED_ON, SYSDATE);
        :NEW.CREATED_BY := COALESCE(:NEW.CREATED_BY, l_user);
    END IF;

    :NEW.EMPLOYEE_CODE := UPPER(TRIM(:NEW.EMPLOYEE_CODE));
    :NEW.FIRST_NAME := TRIM(:NEW.FIRST_NAME);
    :NEW.LAST_NAME := TRIM(:NEW.LAST_NAME);
    :NEW.CNIC := TRIM(:NEW.CNIC);
    :NEW.EMAIL := LOWER(TRIM(:NEW.EMAIL));
    :NEW.MOBILE := TRIM(:NEW.MOBILE);
    :NEW.DATE_OF_JOINING := COALESCE(:NEW.DATE_OF_JOINING, TRUNC(SYSDATE));
    :NEW.STATUS := UPPER(COALESCE(TRIM(:NEW.STATUS), 'ACTIVE'));
    :NEW.UPDATED_ON := SYSDATE;
    :NEW.UPDATED_BY := l_user;
END;
/
