CREATE TABLE HRMS_DEPARTMENTS (
    DEPARTMENT_ID         NUMBER,
    DEPARTMENT_CODE       VARCHAR2(30)  CONSTRAINT HRMSDEPT_CODE_NN NOT NULL,
    DEPARTMENT_NAME       VARCHAR2(200) CONSTRAINT HRMSDEPT_NAME_NN NOT NULL,
    DESCRIPTION           VARCHAR2(1000),
    PARENT_DEPARTMENT_ID  NUMBER,
    LOCATION_ID           NUMBER,
    COST_CENTER           VARCHAR2(50),
    IS_ACTIVE             VARCHAR2(1) DEFAULT 'Y' CONSTRAINT HRMSDEPT_ACTIVE_NN NOT NULL,
    START_DATE            DATE DEFAULT TRUNC(SYSDATE) CONSTRAINT HRMSDEPT_START_NN NOT NULL,
    END_DATE              DATE,
    CREATED_BY            VARCHAR2(150),
    CREATED_ON            DATE DEFAULT SYSDATE,
    UPDATED_BY            VARCHAR2(150),
    UPDATED_ON            DATE DEFAULT SYSDATE,
    CONSTRAINT HRMSDEPT_DEPTID_PK PRIMARY KEY (DEPARTMENT_ID),
    CONSTRAINT HRMSDEPT_CODE_UK UNIQUE (DEPARTMENT_CODE),
    CONSTRAINT HRMSDEPT_PARENT_FK FOREIGN KEY (PARENT_DEPARTMENT_ID)
        REFERENCES HRMS_DEPARTMENTS (DEPARTMENT_ID),
    CONSTRAINT HRMSDEPT_LOC_FK FOREIGN KEY (LOCATION_ID)
        REFERENCES HRMS_LOCATIONS (LOCATION_ID),
    CONSTRAINT HRMSDEPT_ACTIVE_CK CHECK (IS_ACTIVE IN ('Y', 'N')),
    CONSTRAINT HRMSDEPT_DATES_CK CHECK (END_DATE IS NULL OR END_DATE >= START_DATE),
    CONSTRAINT HRMSDEPT_PARENT_CK CHECK (PARENT_DEPARTMENT_ID IS NULL OR PARENT_DEPARTMENT_ID <> DEPARTMENT_ID)
);

CREATE SEQUENCE HRMS_DEPARTMENTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX HRMSDEPT_PARENT_IX ON HRMS_DEPARTMENTS (PARENT_DEPARTMENT_ID);
CREATE INDEX HRMSDEPT_LOC_IX ON HRMS_DEPARTMENTS (LOCATION_ID);
CREATE INDEX HRMSDEPT_ACTIVE_IX ON HRMS_DEPARTMENTS (IS_ACTIVE, DEPARTMENT_NAME);
CREATE INDEX HRMSDEPT_COST_CENTER_IX ON HRMS_DEPARTMENTS (COST_CENTER);

CREATE OR REPLACE TRIGGER HRMSDEPT_BIUR
    BEFORE INSERT OR UPDATE ON HRMS_DEPARTMENTS
    FOR EACH ROW
DECLARE
    l_user VARCHAR2(150);
BEGIN
    l_user := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), USER);

    IF INSERTING THEN
        IF :NEW.DEPARTMENT_ID IS NULL THEN
            :NEW.DEPARTMENT_ID := HRMS_DEPARTMENTS_SEQ.NEXTVAL;
        END IF;

        :NEW.CREATED_ON := COALESCE(:NEW.CREATED_ON, SYSDATE);
        :NEW.CREATED_BY := COALESCE(:NEW.CREATED_BY, l_user);
    END IF;

    :NEW.DEPARTMENT_CODE := UPPER(TRIM(:NEW.DEPARTMENT_CODE));
    :NEW.DEPARTMENT_NAME := TRIM(:NEW.DEPARTMENT_NAME);
    :NEW.DESCRIPTION := TRIM(:NEW.DESCRIPTION);
    :NEW.COST_CENTER := UPPER(TRIM(:NEW.COST_CENTER));
    :NEW.IS_ACTIVE := UPPER(COALESCE(TRIM(:NEW.IS_ACTIVE), 'Y'));
    :NEW.START_DATE := COALESCE(:NEW.START_DATE, TRUNC(SYSDATE));
    :NEW.UPDATED_ON := SYSDATE;
    :NEW.UPDATED_BY := l_user;
END;
/
