CREATE TABLE HRMS_EMPLOYEE_CONTACTS (
    CONTACT_ID     NUMBER,
    EMPLOYEE_ID    NUMBER CONSTRAINT HRMSECON_EMP_NN NOT NULL,
    CONTACT_TYPE   VARCHAR2(30) CONSTRAINT HRMSECON_TYPE_NN NOT NULL,
    CONTACT_VALUE  VARCHAR2(300) CONSTRAINT HRMSECON_VALUE_NN NOT NULL,
    IS_PRIMARY     VARCHAR2(1) DEFAULT 'N' CONSTRAINT HRMSECON_PRIMARY_NN NOT NULL,
    CREATED_BY     VARCHAR2(150),
    CREATED_ON     DATE DEFAULT SYSDATE,
    UPDATED_BY     VARCHAR2(150),
    UPDATED_ON     DATE DEFAULT SYSDATE,
    CONSTRAINT HRMSECON_CONID_PK PRIMARY KEY (CONTACT_ID),
    CONSTRAINT HRMSECON_EMP_FK FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES HRMS_EMPLOYEES (EMPLOYEE_ID)
        ON DELETE CASCADE,
    CONSTRAINT HRMSECON_TYPE_CK CHECK (CONTACT_TYPE IN ('EMAIL', 'MOBILE', 'PHONE', 'ADDRESS', 'EMERGENCY')),
    CONSTRAINT HRMSECON_PRIMARY_CK CHECK (IS_PRIMARY IN ('Y', 'N'))
);

CREATE SEQUENCE HRMS_EMPLOYEE_CONTACTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE INDEX HRMSECON_EMP_IX ON HRMS_EMPLOYEE_CONTACTS (EMPLOYEE_ID);

CREATE OR REPLACE TRIGGER HRMSECON_BIUR
    BEFORE INSERT OR UPDATE ON HRMS_EMPLOYEE_CONTACTS
    FOR EACH ROW
DECLARE
    l_user VARCHAR2(150);
BEGIN
    l_user := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), USER);

    IF INSERTING THEN
        IF :NEW.CONTACT_ID IS NULL THEN
            :NEW.CONTACT_ID := HRMS_EMPLOYEE_CONTACTS_SEQ.NEXTVAL;
        END IF;
        :NEW.CREATED_ON := COALESCE(:NEW.CREATED_ON, SYSDATE);
        :NEW.CREATED_BY := COALESCE(:NEW.CREATED_BY, l_user);
    END IF;

    :NEW.CONTACT_TYPE := UPPER(TRIM(:NEW.CONTACT_TYPE));
    :NEW.CONTACT_VALUE := TRIM(:NEW.CONTACT_VALUE);
    :NEW.IS_PRIMARY := UPPER(COALESCE(TRIM(:NEW.IS_PRIMARY), 'N'));
    :NEW.UPDATED_ON := SYSDATE;
    :NEW.UPDATED_BY := l_user;
END;
/
