CREATE TABLE HRMS_EMPLOYMENT_TYPES (
    EMPLOYMENT_TYPE_ID    NUMBER,
    EMPLOYMENT_TYPE_CODE  VARCHAR2(30)  CONSTRAINT HRMSET_CODE_NN NOT NULL,
    EMPLOYMENT_TYPE_NAME  VARCHAR2(200) CONSTRAINT HRMSET_NAME_NN NOT NULL,
    DESCRIPTION           VARCHAR2(1000),
    IS_ACTIVE             VARCHAR2(1) DEFAULT 'Y' CONSTRAINT HRMSET_ACTIVE_NN NOT NULL,
    CREATED_BY            VARCHAR2(150),
    CREATED_ON            DATE DEFAULT SYSDATE,
    UPDATED_BY            VARCHAR2(150),
    UPDATED_ON            DATE DEFAULT SYSDATE,
    CONSTRAINT HRMSET_EMPTYPEID_PK PRIMARY KEY (EMPLOYMENT_TYPE_ID),
    CONSTRAINT HRMSET_CODE_UK UNIQUE (EMPLOYMENT_TYPE_CODE),
    CONSTRAINT HRMSET_ACTIVE_CK CHECK (IS_ACTIVE IN ('Y', 'N'))
);

CREATE SEQUENCE HRMS_EMPLOYMENT_TYPES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX HRMSET_ACTIVE_IX ON HRMS_EMPLOYMENT_TYPES (IS_ACTIVE, EMPLOYMENT_TYPE_NAME);

CREATE OR REPLACE TRIGGER HRMSET_BIUR
    BEFORE INSERT OR UPDATE ON HRMS_EMPLOYMENT_TYPES
    FOR EACH ROW
DECLARE
    l_user VARCHAR2(150);
BEGIN
    l_user := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), USER);

    IF INSERTING THEN
        IF :NEW.EMPLOYMENT_TYPE_ID IS NULL THEN
            :NEW.EMPLOYMENT_TYPE_ID := HRMS_EMPLOYMENT_TYPES_SEQ.NEXTVAL;
        END IF;

        :NEW.CREATED_ON := COALESCE(:NEW.CREATED_ON, SYSDATE);
        :NEW.CREATED_BY := COALESCE(:NEW.CREATED_BY, l_user);
    END IF;

    :NEW.EMPLOYMENT_TYPE_CODE := UPPER(TRIM(:NEW.EMPLOYMENT_TYPE_CODE));
    :NEW.EMPLOYMENT_TYPE_NAME := TRIM(:NEW.EMPLOYMENT_TYPE_NAME);
    :NEW.DESCRIPTION := TRIM(:NEW.DESCRIPTION);
    :NEW.IS_ACTIVE := UPPER(COALESCE(TRIM(:NEW.IS_ACTIVE), 'Y'));
    :NEW.UPDATED_ON := SYSDATE;
    :NEW.UPDATED_BY := l_user;
END;
/
