CREATE TABLE ADMIN.HRMS_LOCATIONS (
    LOCATION_ID    NUMBER,
    LOCATION_CODE  VARCHAR2(30)  CONSTRAINT HRMSLOC_CODE_NN NOT NULL,
    LOCATION_NAME  VARCHAR2(200) CONSTRAINT HRMSLOC_NAME_NN NOT NULL,
    ADDRESS_LINE1  VARCHAR2(300),
    ADDRESS_LINE2  VARCHAR2(300),
    CITY           VARCHAR2(100),
    STATE_PROVINCE VARCHAR2(100),
    COUNTRY        VARCHAR2(100),
    POSTAL_CODE    VARCHAR2(30),
    IS_ACTIVE      VARCHAR2(1) DEFAULT 'Y' CONSTRAINT HRMSLOC_ACTIVE_NN NOT NULL,
    CREATED_BY     VARCHAR2(150),
    CREATED_ON     DATE DEFAULT SYSDATE,
    UPDATED_BY     VARCHAR2(150),
    UPDATED_ON     DATE DEFAULT SYSDATE,
    CONSTRAINT HRMSLOC_LOCID_PK PRIMARY KEY (LOCATION_ID),
    CONSTRAINT HRMSLOC_CODE_UK UNIQUE (LOCATION_CODE),
    CONSTRAINT HRMSLOC_ACTIVE_CK CHECK (IS_ACTIVE IN ('Y', 'N'))
);

CREATE SEQUENCE ADMIN.HRMS_LOCATIONS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX ADMIN.HRMSLOC_ACTIVE_IX ON ADMIN.HRMS_LOCATIONS (IS_ACTIVE, LOCATION_NAME);

CREATE OR REPLACE TRIGGER ADMIN.HRMSLOC_BIUR
    BEFORE INSERT OR UPDATE ON ADMIN.HRMS_LOCATIONS
    FOR EACH ROW
DECLARE
    l_user VARCHAR2(150);
BEGIN
    l_user := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), USER);

    IF INSERTING THEN
        IF :NEW.LOCATION_ID IS NULL THEN
            :NEW.LOCATION_ID := ADMIN.HRMS_LOCATIONS_SEQ.NEXTVAL;
        END IF;

        :NEW.CREATED_ON := COALESCE(:NEW.CREATED_ON, SYSDATE);
        :NEW.CREATED_BY := COALESCE(:NEW.CREATED_BY, l_user);
    END IF;

    :NEW.LOCATION_CODE := UPPER(TRIM(:NEW.LOCATION_CODE));
    :NEW.LOCATION_NAME := TRIM(:NEW.LOCATION_NAME);
    :NEW.IS_ACTIVE := UPPER(COALESCE(TRIM(:NEW.IS_ACTIVE), 'Y'));
    :NEW.UPDATED_ON := SYSDATE;
    :NEW.UPDATED_BY := l_user;
END;
/
