CREATE TABLE HRMS_EMPLOYEES (
    EMPLOYEE_ID          NUMBER,
    EMPLOYEE_NUMBER      VARCHAR2(30)  CONSTRAINT HRMSEMP_NUMBER_NN NOT NULL,
    FIRST_NAME           VARCHAR2(100) CONSTRAINT HRMSEMP_FIRST_NAME_NN NOT NULL,
    MIDDLE_NAME          VARCHAR2(100),
    LAST_NAME            VARCHAR2(100) CONSTRAINT HRMSEMP_LAST_NAME_NN NOT NULL,
    EMAIL                VARCHAR2(200) CONSTRAINT HRMSEMP_EMAIL_NN NOT NULL,
    PHONE_NUMBER         VARCHAR2(50),
    HIRE_DATE            DATE DEFAULT TRUNC(SYSDATE) CONSTRAINT HRMSEMP_HIRE_DATE_NN NOT NULL,
    JOB_TITLE            VARCHAR2(150),
    DEPARTMENT_NAME      VARCHAR2(150),
    MANAGER_EMPLOYEE_ID  NUMBER,
    EMPLOYMENT_STATUS    VARCHAR2(30) DEFAULT 'ACTIVE' CONSTRAINT HRMSEMP_STATUS_NN NOT NULL,
    CREATED_BY           VARCHAR2(150),
    CREATED_ON           DATE DEFAULT SYSDATE,
    UPDATED_BY           VARCHAR2(150),
    UPDATED_ON           DATE DEFAULT SYSDATE,
    CONSTRAINT HRMSEMP_EMPID_PK PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT HRMSEMP_NUMBER_UK UNIQUE (EMPLOYEE_NUMBER),
    CONSTRAINT HRMSEMP_EMAIL_UK UNIQUE (EMAIL),
    CONSTRAINT HRMSEMP_MANAGER_FK FOREIGN KEY (MANAGER_EMPLOYEE_ID)
        REFERENCES HRMS_EMPLOYEES (EMPLOYEE_ID),
    CONSTRAINT HRMSEMP_STATUS_CK CHECK (EMPLOYMENT_STATUS IN ('ACTIVE', 'INACTIVE', 'TERMINATED')),
    CONSTRAINT HRMSEMP_MANAGER_CK CHECK (MANAGER_EMPLOYEE_ID IS NULL OR MANAGER_EMPLOYEE_ID <> EMPLOYEE_ID)
);

CREATE SEQUENCE HRMS_EMPLOYEES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX HRMSEMP_NAME_IX
    ON HRMS_EMPLOYEES (LAST_NAME, FIRST_NAME);

CREATE INDEX HRMSEMP_MANAGER_IX
    ON HRMS_EMPLOYEES (MANAGER_EMPLOYEE_ID);

CREATE INDEX HRMSEMP_STATUS_IX
    ON HRMS_EMPLOYEES (EMPLOYMENT_STATUS);

CREATE OR REPLACE TRIGGER HRMSEMP_BIUR
    BEFORE INSERT OR UPDATE ON HRMS_EMPLOYEES
    FOR EACH ROW
DECLARE
    l_user VARCHAR2(150);
BEGIN
    l_user := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), USER);

    IF INSERTING THEN
        IF :NEW.EMPLOYEE_ID IS NULL THEN
            :NEW.EMPLOYEE_ID := HRMS_EMPLOYEES_SEQ.NEXTVAL;
        END IF;

        :NEW.CREATED_ON := COALESCE(:NEW.CREATED_ON, SYSDATE);
        :NEW.CREATED_BY := COALESCE(:NEW.CREATED_BY, l_user);
    END IF;

    :NEW.EMPLOYEE_NUMBER := UPPER(TRIM(:NEW.EMPLOYEE_NUMBER));
    :NEW.FIRST_NAME := TRIM(:NEW.FIRST_NAME);
    :NEW.MIDDLE_NAME := TRIM(:NEW.MIDDLE_NAME);
    :NEW.LAST_NAME := TRIM(:NEW.LAST_NAME);
    :NEW.EMAIL := LOWER(TRIM(:NEW.EMAIL));
    :NEW.PHONE_NUMBER := TRIM(:NEW.PHONE_NUMBER);
    :NEW.JOB_TITLE := TRIM(:NEW.JOB_TITLE);
    :NEW.DEPARTMENT_NAME := TRIM(:NEW.DEPARTMENT_NAME);
    :NEW.EMPLOYMENT_STATUS := UPPER(COALESCE(TRIM(:NEW.EMPLOYMENT_STATUS), 'ACTIVE'));
    :NEW.UPDATED_ON := SYSDATE;
    :NEW.UPDATED_BY := l_user;
END;
/
