CREATE TABLE ADMIN.HRMS_EMPLOYEE_DEPENDENTS (
    DEPENDENT_ID      NUMBER,
    EMPLOYEE_ID       NUMBER CONSTRAINT HRMSEDEP_EMP_NN NOT NULL,
    FULL_NAME         VARCHAR2(200) CONSTRAINT HRMSEDEP_NAME_NN NOT NULL,
    RELATIONSHIP      VARCHAR2(50) CONSTRAINT HRMSEDEP_REL_NN NOT NULL,
    DATE_OF_BIRTH     DATE,
    CNIC              VARCHAR2(20),
    IS_ACTIVE         VARCHAR2(1) DEFAULT 'Y' CONSTRAINT HRMSEDEP_ACTIVE_NN NOT NULL,
    CREATED_BY        VARCHAR2(150),
    CREATED_ON        DATE DEFAULT SYSDATE,
    UPDATED_BY        VARCHAR2(150),
    UPDATED_ON        DATE DEFAULT SYSDATE,
    CONSTRAINT HRMSEDEP_DEPID_PK PRIMARY KEY (DEPENDENT_ID),
    CONSTRAINT HRMSEDEP_EMP_FK FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES ADMIN.HRMS_EMPLOYEES (EMPLOYEE_ID)
        ON DELETE CASCADE,
    CONSTRAINT HRMSEDEP_ACTIVE_CK CHECK (IS_ACTIVE IN ('Y', 'N'))
);

CREATE SEQUENCE ADMIN.HRMS_EMPLOYEE_DEPENDENTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE INDEX ADMIN.HRMSEDEP_EMP_IX ON ADMIN.HRMS_EMPLOYEE_DEPENDENTS (EMPLOYEE_ID);

CREATE OR REPLACE TRIGGER ADMIN.HRMSEDEP_BIUR
    BEFORE INSERT OR UPDATE ON ADMIN.HRMS_EMPLOYEE_DEPENDENTS
    FOR EACH ROW
DECLARE
    l_user VARCHAR2(150);
BEGIN
    l_user := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), USER);

    IF INSERTING THEN
        IF :NEW.DEPENDENT_ID IS NULL THEN
            :NEW.DEPENDENT_ID := ADMIN.HRMS_EMPLOYEE_DEPENDENTS_SEQ.NEXTVAL;
        END IF;
        :NEW.CREATED_ON := COALESCE(:NEW.CREATED_ON, SYSDATE);
        :NEW.CREATED_BY := COALESCE(:NEW.CREATED_BY, l_user);
    END IF;

    :NEW.FULL_NAME := TRIM(:NEW.FULL_NAME);
    :NEW.RELATIONSHIP := UPPER(TRIM(:NEW.RELATIONSHIP));
    :NEW.CNIC := TRIM(:NEW.CNIC);
    :NEW.IS_ACTIVE := UPPER(COALESCE(TRIM(:NEW.IS_ACTIVE), 'Y'));
    :NEW.UPDATED_ON := SYSDATE;
    :NEW.UPDATED_BY := l_user;
END;
/
