CREATE TABLE HRMS_DESIGNATIONS (
    DESIGNATION_ID    NUMBER,
    DESIGNATION_CODE  VARCHAR2(30)  CONSTRAINT HRMSDSG_CODE_NN NOT NULL,
    DESIGNATION_NAME  VARCHAR2(200) CONSTRAINT HRMSDSG_NAME_NN NOT NULL,
    DESCRIPTION       VARCHAR2(1000),
    IS_ACTIVE         VARCHAR2(1) DEFAULT 'Y' CONSTRAINT HRMSDSG_ACTIVE_NN NOT NULL,
    CREATED_BY        VARCHAR2(150),
    CREATED_ON        DATE DEFAULT SYSDATE,
    UPDATED_BY        VARCHAR2(150),
    UPDATED_ON        DATE DEFAULT SYSDATE,
    CONSTRAINT HRMSDSG_DSGID_PK PRIMARY KEY (DESIGNATION_ID),
    CONSTRAINT HRMSDSG_CODE_UK UNIQUE (DESIGNATION_CODE),
    CONSTRAINT HRMSDSG_ACTIVE_CK CHECK (IS_ACTIVE IN ('Y', 'N'))
);

CREATE SEQUENCE HRMS_DESIGNATIONS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX HRMSDSG_ACTIVE_IX ON HRMS_DESIGNATIONS (IS_ACTIVE, DESIGNATION_NAME);

CREATE OR REPLACE TRIGGER HRMSDSG_BIUR
    BEFORE INSERT OR UPDATE ON HRMS_DESIGNATIONS
    FOR EACH ROW
DECLARE
    l_user VARCHAR2(150);
BEGIN
    l_user := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), USER);

    IF INSERTING THEN
        IF :NEW.DESIGNATION_ID IS NULL THEN
            :NEW.DESIGNATION_ID := HRMS_DESIGNATIONS_SEQ.NEXTVAL;
        END IF;

        :NEW.CREATED_ON := COALESCE(:NEW.CREATED_ON, SYSDATE);
        :NEW.CREATED_BY := COALESCE(:NEW.CREATED_BY, l_user);
    END IF;

    :NEW.DESIGNATION_CODE := UPPER(TRIM(:NEW.DESIGNATION_CODE));
    :NEW.DESIGNATION_NAME := TRIM(:NEW.DESIGNATION_NAME);
    :NEW.DESCRIPTION := TRIM(:NEW.DESCRIPTION);
    :NEW.IS_ACTIVE := UPPER(COALESCE(TRIM(:NEW.IS_ACTIVE), 'Y'));
    :NEW.UPDATED_ON := SYSDATE;
    :NEW.UPDATED_BY := l_user;
END;
/
