CREATE TABLE HRMS_EMPLOYEES (
    EMPLOYEE_ID NUMBER,
    FIRST_NAME  VARCHAR2(100) CONSTRAINT HRMSSMP_FIRSTNAME_NN NOT NULL,
    LAST_NAME   VARCHAR2(100) CONSTRAINT HRMSSMP_LASTNAME_NN NOT NULL,
    EMAIL       VARCHAR2(200) CONSTRAINT HRMSSMP_EMAIL_NN NOT NULL,
    CREATED     DATE DEFAULT SYSDATE,
    CREATED_BY  VARCHAR2(150),
    UPDATED     DATE DEFAULT SYSDATE,
    UPDATED_BY  VARCHAR2(150),
    CONSTRAINT HRMSEMP_EMPID_PK PRIMARY KEY(EMPLOYEE_ID)
);