CREATE TABLE ADMIN.HRMS_EMPLOYEE_DOCUMENTS (
    DOCUMENT_ID     NUMBER,
    EMPLOYEE_ID     NUMBER CONSTRAINT HRMSEDOC_EMP_NN NOT NULL,
    DOCUMENT_TYPE   VARCHAR2(50) CONSTRAINT HRMSEDOC_TYPE_NN NOT NULL,
    DOCUMENT_NUMBER VARCHAR2(100),
    FILE_NAME       VARCHAR2(255),
    MIME_TYPE       VARCHAR2(255),
    FILE_BLOB       BLOB,
    ISSUE_DATE      DATE,
    EXPIRY_DATE     DATE,
    CREATED_BY      VARCHAR2(150),
    CREATED_ON      DATE DEFAULT SYSDATE,
    UPDATED_BY      VARCHAR2(150),
    UPDATED_ON      DATE DEFAULT SYSDATE,
    CONSTRAINT HRMSEDOC_DOCID_PK PRIMARY KEY (DOCUMENT_ID),
    CONSTRAINT HRMSEDOC_EMP_FK FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES ADMIN.HRMS_EMPLOYEES (EMPLOYEE_ID)
        ON DELETE CASCADE,
    CONSTRAINT HRMSEDOC_DATES_CK CHECK (EXPIRY_DATE IS NULL OR ISSUE_DATE IS NULL OR EXPIRY_DATE >= ISSUE_DATE)
);

CREATE SEQUENCE ADMIN.HRMS_EMPLOYEE_DOCUMENTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE INDEX ADMIN.HRMSEDOC_EMP_IX ON ADMIN.HRMS_EMPLOYEE_DOCUMENTS (EMPLOYEE_ID);
CREATE INDEX ADMIN.HRMSEDOC_TYPE_IX ON ADMIN.HRMS_EMPLOYEE_DOCUMENTS (DOCUMENT_TYPE);

CREATE OR REPLACE TRIGGER ADMIN.HRMSEDOC_BIUR
    BEFORE INSERT OR UPDATE ON ADMIN.HRMS_EMPLOYEE_DOCUMENTS
    FOR EACH ROW
DECLARE
    l_user VARCHAR2(150);
BEGIN
    l_user := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), USER);

    IF INSERTING THEN
        IF :NEW.DOCUMENT_ID IS NULL THEN
            :NEW.DOCUMENT_ID := ADMIN.HRMS_EMPLOYEE_DOCUMENTS_SEQ.NEXTVAL;
        END IF;
        :NEW.CREATED_ON := COALESCE(:NEW.CREATED_ON, SYSDATE);
        :NEW.CREATED_BY := COALESCE(:NEW.CREATED_BY, l_user);
    END IF;

    :NEW.DOCUMENT_TYPE := UPPER(TRIM(:NEW.DOCUMENT_TYPE));
    :NEW.DOCUMENT_NUMBER := UPPER(TRIM(:NEW.DOCUMENT_NUMBER));
    :NEW.FILE_NAME := TRIM(:NEW.FILE_NAME);
    :NEW.MIME_TYPE := TRIM(:NEW.MIME_TYPE);
    :NEW.UPDATED_ON := SYSDATE;
    :NEW.UPDATED_BY := l_user;
END;
/
