CREATE TABLE ADMIN.HRMS_GRADES (
    GRADE_ID    NUMBER,
    GRADE_CODE  VARCHAR2(30)  CONSTRAINT HRMSGRADE_CODE_NN NOT NULL,
    GRADE_NAME  VARCHAR2(200) CONSTRAINT HRMSGRADE_NAME_NN NOT NULL,
    MIN_SALARY  NUMBER(14,2),
    MAX_SALARY  NUMBER(14,2),
    IS_ACTIVE   VARCHAR2(1) DEFAULT 'Y' CONSTRAINT HRMSGRADE_ACTIVE_NN NOT NULL,
    CREATED_BY  VARCHAR2(150),
    CREATED_ON  DATE DEFAULT SYSDATE,
    UPDATED_BY  VARCHAR2(150),
    UPDATED_ON  DATE DEFAULT SYSDATE,
    CONSTRAINT HRMSGRADE_GRADEID_PK PRIMARY KEY (GRADE_ID),
    CONSTRAINT HRMSGRADE_CODE_UK UNIQUE (GRADE_CODE),
    CONSTRAINT HRMSGRADE_ACTIVE_CK CHECK (IS_ACTIVE IN ('Y', 'N')),
    CONSTRAINT HRMSGRADE_SALARY_CK CHECK (MAX_SALARY IS NULL OR MIN_SALARY IS NULL OR MAX_SALARY >= MIN_SALARY)
);

CREATE SEQUENCE ADMIN.HRMS_GRADES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX ADMIN.HRMSGRADE_ACTIVE_IX ON ADMIN.HRMS_GRADES (IS_ACTIVE, GRADE_NAME);

CREATE OR REPLACE TRIGGER ADMIN.HRMSGRADE_BIUR
    BEFORE INSERT OR UPDATE ON ADMIN.HRMS_GRADES
    FOR EACH ROW
DECLARE
    l_user VARCHAR2(150);
BEGIN
    l_user := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), USER);

    IF INSERTING THEN
        IF :NEW.GRADE_ID IS NULL THEN
            :NEW.GRADE_ID := ADMIN.HRMS_GRADES_SEQ.NEXTVAL;
        END IF;

        :NEW.CREATED_ON := COALESCE(:NEW.CREATED_ON, SYSDATE);
        :NEW.CREATED_BY := COALESCE(:NEW.CREATED_BY, l_user);
    END IF;

    :NEW.GRADE_CODE := UPPER(TRIM(:NEW.GRADE_CODE));
    :NEW.GRADE_NAME := TRIM(:NEW.GRADE_NAME);
    :NEW.IS_ACTIVE := UPPER(COALESCE(TRIM(:NEW.IS_ACTIVE), 'Y'));
    :NEW.UPDATED_ON := SYSDATE;
    :NEW.UPDATED_BY := l_user;
END;
/
