CREATE TABLE ADMIN.HRMS_LOOKUP_TYPES (
    LOOKUP_TYPE_ID    NUMBER,
    LOOKUP_TYPE_CODE  VARCHAR2(100)  CONSTRAINT HRMSLKT_CODE_NN NOT NULL,
    LOOKUP_TYPE_NAME  VARCHAR2(200)  CONSTRAINT HRMSLKT_NAME_NN NOT NULL,
    DESCRIPTION       VARCHAR2(1000),
    DISPLAY_SEQUENCE  NUMBER DEFAULT 10 CONSTRAINT HRMSLKT_SEQ_NN NOT NULL,
    IS_ACTIVE         VARCHAR2(1) DEFAULT 'Y' CONSTRAINT HRMSLKT_ACTIVE_NN NOT NULL,
    CREATED           DATE DEFAULT SYSDATE,
    CREATED_BY        VARCHAR2(150),
    UPDATED           DATE DEFAULT SYSDATE,
    UPDATED_BY        VARCHAR2(150),
    CONSTRAINT HRMSLKT_LKTID_PK PRIMARY KEY (LOOKUP_TYPE_ID),
    CONSTRAINT HRMSLKT_CODE_UK UNIQUE (LOOKUP_TYPE_CODE),
    CONSTRAINT HRMSLKT_ACTIVE_CK CHECK (IS_ACTIVE IN ('Y', 'N'))
);

CREATE TABLE ADMIN.HRMS_LOOKUP_VALUES (
    LOOKUP_VALUE_ID    NUMBER,
    LOOKUP_TYPE_ID     NUMBER CONSTRAINT HRMSLKV_LKTID_NN NOT NULL,
    LOOKUP_VALUE_CODE  VARCHAR2(100)  CONSTRAINT HRMSLKV_CODE_NN NOT NULL,
    LOOKUP_VALUE_NAME  VARCHAR2(200)  CONSTRAINT HRMSLKV_NAME_NN NOT NULL,
    DESCRIPTION        VARCHAR2(1000),
    DISPLAY_SEQUENCE   NUMBER DEFAULT 10 CONSTRAINT HRMSLKV_SEQ_NN NOT NULL,
    IS_ACTIVE          VARCHAR2(1) DEFAULT 'Y' CONSTRAINT HRMSLKV_ACTIVE_NN NOT NULL,
    START_DATE         DATE,
    END_DATE           DATE,
    CREATED            DATE DEFAULT SYSDATE,
    CREATED_BY         VARCHAR2(150),
    UPDATED            DATE DEFAULT SYSDATE,
    UPDATED_BY         VARCHAR2(150),
    CONSTRAINT HRMSLKV_LKVID_PK PRIMARY KEY (LOOKUP_VALUE_ID),
    CONSTRAINT HRMSLKV_LKTID_FK FOREIGN KEY (LOOKUP_TYPE_ID)
        REFERENCES ADMIN.HRMS_LOOKUP_TYPES (LOOKUP_TYPE_ID)
        ON DELETE CASCADE,
    CONSTRAINT HRMSLKV_CODE_UK UNIQUE (LOOKUP_TYPE_ID, LOOKUP_VALUE_CODE),
    CONSTRAINT HRMSLKV_ACTIVE_CK CHECK (IS_ACTIVE IN ('Y', 'N')),
    CONSTRAINT HRMSLKV_DATES_CK CHECK (END_DATE IS NULL OR START_DATE IS NULL OR END_DATE >= START_DATE)
);

CREATE SEQUENCE ADMIN.HRMS_LOOKUP_TYPES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ADMIN.HRMS_LOOKUP_VALUES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX ADMIN.HRMSLKV_LKTID_IX
    ON ADMIN.HRMS_LOOKUP_VALUES (LOOKUP_TYPE_ID);

CREATE INDEX ADMIN.HRMSLKV_ACTIVE_IX
    ON ADMIN.HRMS_LOOKUP_VALUES (LOOKUP_TYPE_ID, IS_ACTIVE, DISPLAY_SEQUENCE);

CREATE OR REPLACE TRIGGER ADMIN.HRMSLKT_BIUR
    BEFORE INSERT OR UPDATE ON ADMIN.HRMS_LOOKUP_TYPES
    FOR EACH ROW
DECLARE
    l_user VARCHAR2(150);
BEGIN
    l_user := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), USER);

    IF INSERTING THEN
        IF :NEW.LOOKUP_TYPE_ID IS NULL THEN
            :NEW.LOOKUP_TYPE_ID := ADMIN.HRMS_LOOKUP_TYPES_SEQ.NEXTVAL;
        END IF;

        :NEW.CREATED := COALESCE(:NEW.CREATED, SYSDATE);
        :NEW.CREATED_BY := COALESCE(:NEW.CREATED_BY, l_user);
    END IF;

    :NEW.LOOKUP_TYPE_CODE := UPPER(TRIM(:NEW.LOOKUP_TYPE_CODE));
    :NEW.LOOKUP_TYPE_NAME := TRIM(:NEW.LOOKUP_TYPE_NAME);
    :NEW.IS_ACTIVE := COALESCE(:NEW.IS_ACTIVE, 'Y');
    :NEW.UPDATED := SYSDATE;
    :NEW.UPDATED_BY := l_user;
END;
/


CREATE OR REPLACE TRIGGER ADMIN.HRMSLKV_BIUR
    BEFORE INSERT OR UPDATE ON ADMIN.HRMS_LOOKUP_VALUES
    FOR EACH ROW
DECLARE
    l_user VARCHAR2(150);
BEGIN
    l_user := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), USER);

    IF INSERTING THEN
        IF :NEW.LOOKUP_VALUE_ID IS NULL THEN
            :NEW.LOOKUP_VALUE_ID := ADMIN.HRMS_LOOKUP_VALUES_SEQ.NEXTVAL;
        END IF;

        :NEW.CREATED := COALESCE(:NEW.CREATED, SYSDATE);
        :NEW.CREATED_BY := COALESCE(:NEW.CREATED_BY, l_user);
    END IF;

    :NEW.LOOKUP_VALUE_CODE := UPPER(TRIM(:NEW.LOOKUP_VALUE_CODE));
    :NEW.LOOKUP_VALUE_NAME := TRIM(:NEW.LOOKUP_VALUE_NAME);
    :NEW.IS_ACTIVE := COALESCE(:NEW.IS_ACTIVE, 'Y');
    :NEW.UPDATED := SYSDATE;
    :NEW.UPDATED_BY := l_user;
END;
/

